Repository MathiasReker/Delfinen, pull requests merged in 2021-05, with the labels that each got.

#19 Fileservice
  src/main/java/com/app/models/FileService.java
Labels: new-feature

#20 Add jacoco
  pom.xml
  src/test/java/com/app/AppTest.java
Labels: new-feature

#18 Fix lint issues
  assembly.xml
  other/use-cases.md
  pom.xml
Labels: enhancement

#23 Make classes
  src/main/java/com/app/models/.touch
  src/main/java/com/app/models/CompetitionModel.java
  src/main/java/com/app/models/DisciplineModel.java
  src/main/java/com/app/models/Distance.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MembershipModel.java
  src/main/java/com/app/models/PaymentModel.java
  src/main/java/com/app/models/PaymentRequestModel.java
  src/main/java/com/app/models/PaymentStatusModel.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/models/StyleModel.java
  src/main/java/com/app/models/services/FileService.java
Labels: enhancement

#28 Testing
  src/test/java/com/app/AppTest.java
Labels: enhancement

#29 Testing new github actions
  src/test/java/com/app/AppTest.java
Labels: enhancement

#30 Fix jacoco action
  src/test/java/com/app/MainTest.java
Labels: bug-fix

#32 Update gitignore
  .gitignore
Labels: enhancement

#31 Create menu structure
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  .github/workflows/jacoco.yml
  README.md
  other/use-cases.md
  src/main/java/com/app/App.java
  src/main/java/com/app/Main.java
  src/main/java/com/app/controllers/.touch
  src/main/java/com/app/controllers/MenuController.java
  src/main/java/com/app/controllers/menuactions/ExitMenuAction.java
  src/main/java/com/app/controllers/menuactions/MenuActions.java
  src/main/java/com/app/models/MenuModel.java
  src/main/java/com/app/views/.touch
  src/main/java/com/app/views/MenuView.java
  src/main/java/com/app/views/View.java
  src/main/java/com/app/views/utils/ColorKey.java
  src/main/java/com/app/views/utils/ColorText.java
  src/test/java/com/app/AppTest.java
  src/test/java/com/app/MainTest.java
  src/test/java/com/app/views/ViewTest.java
  src/test/java/com/app/views/utils/ColorTextTest.java
Labels: new-feature

#33 Discipline model
  src/main/java/com/app/models/DisciplineModel.java
  src/main/java/com/app/models/Distance.java
  src/main/java/com/app/models/DistanceModel.java
  src/main/java/com/app/models/StyleModel.java
  src/test/java/com/app/models/DisciplineModelTest.java
Labels: new-feature

#35 Member
  src/main/java/com/app/models/GenderModel.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MembershipModel.java
  src/main/java/com/app/models/PaymentStatusModel.java
  src/test/java/com/app/models/MemberModelTest.java
  src/test/java/com/app/models/MembershipModelTest.java
Labels: new-feature

#38 Fix tests
  pom.xml
  src/test/java/com/app/models/DisciplineModelTest.java
  src/test/java/com/app/models/MemberModelTest.java
  src/test/java/com/app/models/MembershipModelTest.java
Labels: bug-fix

#37 first push of compition and result class
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/models/CompetitionModel.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/views/CompetitionView.java
Labels: new-feature

#40 Disciplines
  src/main/java/com/app/controllers/DisciplinesController.java
  src/main/java/com/app/models/DisciplineModel.java
  src/test/java/com/app/controllers/DisciplinesControllerTest.java
Labels: bug-fix, new-feature

#39 Create member UI functionality [WIP]
  pom.xml
  src/main/java/com/app/App.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/menuactions/CreateMemberSubMenuAction.java
  src/main/java/com/app/controllers/menuactions/EditMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/MemberMenuAction.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/views/MemberView.java
  src/main/java/com/app/views/View.java
  src/test/java/com/app/models/MemberModelTest.java
Labels: enhancement, new-feature

#41 Memberrenew WIP
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/models/PricingModel.java
  src/main/java/com/app/models/services/PaymentRequestService.java
Labels: new-feature

#43 Memberrenew - WIP
  data/payment-requests/out.txt
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/menuactions/MemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/RenewalRequestMenuAction.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MemberNotFoundException.java
Labels: bug-fix, enhancement

#44 Member controller
  .gitignore
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/models/ValidateModel.java
  src/test/java/com/app/models/ValidateModelTest.java
Labels: bug-fix, enhancement

#46 Memberrenew
  data/payment-requests/out.txt
  src/main/java/com/app/controllers/MemberController.java
Labels: enhancement

#47 Fix code
  src/main/java/com/app/controllers/DisciplinesController.java
  src/test/java/com/app/controllers/DisciplinesControllerTest.java
Labels: enhancement

#45 Created some stuff regarding competion and fixed validate date [WIP]
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/models/CompetitionModel.java
  src/main/java/com/app/models/services/CompetitionService.java
  src/main/java/com/app/views/CompetitionView.java
Labels: bug-fix, enhancement, new-feature

#51 Fix maven tests
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  README.md
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/models/CompetitionModel.java
  src/main/java/com/app/models/MembershipModel.java
  src/main/java/com/app/models/ResultModel.java
  src/test/java/com/app/models/MemberModelTest.java
  src/test/java/com/app/models/MembershipModelTest.java
  src/test/java/com/app/models/ValidateModelTest.java
Labels: enhancement

#54 Filehandling to binary
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/menuactions/CreateMemberSubMenuAction.java
  src/main/java/com/app/controllers/menuactions/MenuActions.java
  src/main/java/com/app/models/CouldNotLoadMemberExpeption.java
  src/main/java/com/app/models/DisciplineModel.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MembershipModel.java
  src/main/java/com/app/models/services/FileService.java
  src/main/java/com/app/models/services/MemberService.java
Labels: enhancement, new-feature

#53 Added validations
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/menuactions/AddResultSubMenuAction.java
  src/main/java/com/app/models/ValidateModel.java
Labels: enhancement

#55 changed from textfiles to bins
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/models/CompetitionModel.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/models/services/CompetitionService.java
  src/main/java/com/app/models/services/MemberService.java
Labels: enhancement

#58 Top five
  src/main/java/com/app/App.java
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/DisciplinesController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/menuactions/TopResultsMenuAction.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/models/services/CompetitionService.java
  src/main/java/com/app/views/CompetitionView.java
  src/test/java/com/app/controllers/DisciplinesControllerTest.java
  src/test/java/com/app/models/DisciplineModelTest.java
Labels: bug-fix, new-feature

#60 Fix conflict
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/LeaderboardController.java
Labels: bug-fix

#57 Incomreprediction - initial predict income
  src/main/java/com/app/App.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/PredictionController.java
  src/main/java/com/app/controllers/menuactions/PaymentSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/PredictIncomeDefinedMenuAction.java
  src/main/java/com/app/controllers/menuactions/PredictIncomeMenuAction.java
  src/main/java/com/app/models/CouldNotLoadMemberException.java
  src/main/java/com/app/models/CouldNotLoadMemberExpeption.java
  src/main/java/com/app/models/PaymentRequestModel.java
  src/main/java/com/app/views/PredictionView.java
Labels: new-feature

#64 changed add result to compition method
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/InputController.java
  src/test/java/com/app/models/CompetitionModelTest.java
Labels: enhancement

#65 Disc fix
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/DisciplinesController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/models/DisciplineModel.java
  src/main/java/com/app/views/CompetitionView.java
  src/test/java/com/app/controllers/DisciplinesControllerTest.java
  src/test/java/com/app/models/MemberModelTest.java
Labels: bug-fix, enhancement

#69 Add membership Fixes #59 and fixes
  data/config/config.txt
  src/main/java/com/app/App.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MembershipController.java
  src/main/java/com/app/controllers/MenuController.java
  src/main/java/com/app/controllers/PaymentController.java
  src/main/java/com/app/controllers/PredictionController.java
  src/main/java/com/app/controllers/menuactions/AddResultMenuAction.java
  src/main/java/com/app/controllers/menuactions/AnonymizeMenuAction.java
  src/main/java/com/app/controllers/menuactions/CompetitionMenuAction.java
  src/main/java/com/app/controllers/menuactions/CompetitionSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/CreateCompetitionSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/CreateMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/DisplayArrearsMenuAction.java
  src/main/java/com/app/controllers/menuactions/EditMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/ExitMenuAction.java
  src/main/java/com/app/controllers/menuactions/HandlePaymentMenuAction.java
  src/main/java/com/app/controllers/menuactions/MemberSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/MenuAction.java
  src/main/java/com/app/controllers/menuactions/PaymentRequestMenuAction.java
  src/main/java/com/app/controllers/menuactions/PaymentSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/PredictIncomeDefinedMenuAction.java
  src/main/java/com/app/controllers/menuactions/PredictIncomeMenuAction.java
  src/main/java/com/app/controllers/menuactions/RenewalRequestMenuAction.java
  src/main/java/com/app/controllers/menuactions/SearchMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/TopResultsMenuAction.java
  src/main/java/com/app/controllers/menuactions/ViewMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/ViewResultsMenuAction.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MembershipModel.java
  src/main/java/com/app/models/MenuModel.java
  src/main/java/com/app/models/PaymentModel.java
  src/main/java/com/app/models/PricingModel.java
  src/main/java/com/app/views/PaymentsView.java
  src/test/java/com/app/controllers/PaymentControllerTest.java
  src/test/java/com/app/models/MemberModelTest.java
Labels: bug-fix, enhancement, new-feature

#68 Change results
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/views/CompetitionView.java
Labels: enhancement, new-feature

#71 fixed scanner bug
  src/main/java/com/app/controllers/InputController.java
Labels: bug-fix

#75 minor improvements
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/DisciplinesController.java
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MembershipController.java
  src/main/java/com/app/controllers/PaymentController.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/exceptions/MemberNotFoundException.java
Labels: enhancement

#73 add getter
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/PricingModel.java
  src/main/java/com/app/models/types/AgeGroupType.java
Labels: new-feature

#70 Fix config
  data/config/config.txt
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/PaymentController.java
Labels: bug-fix

#72 Refactor MemberController
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/menuactions/AnonymizeMenuAction.java
  src/main/java/com/app/controllers/menuactions/EditMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/ViewMemberMenuAction.java
Labels: enhancement

#83 Created some views for user
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/views/CompetitionView.java
Labels: enhancement

#90 Passive membership
  other/ClassDiagram.md
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MembershipController.java
  src/main/java/com/app/models/PricingModel.java
Labels: enhancement, new-feature

#87 Refactoreded save/load object services
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/models/services/CompetitionService.java
  src/main/java/com/app/models/services/MemberService.java
  src/main/java/com/app/models/services/ObjectService.java
Labels: enhancement

#82 Top five
  src/main/java/com/app/controllers/LeaderboardController.java
Labels: enhancement, new-feature

#91 Membercleanup
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MembershipController.java
  src/main/java/com/app/models/PricingModel.java
Labels: enhancement

#88 Softcode PricingModel
  src/main/java/com/app/controllers/PredictionController.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/PricingModel.java
  src/main/java/com/app/models/services/PaymentRequestService.java
  src/main/java/com/app/models/types/AgeGroupType.java
Labels: bug-fix, enhancement

#93 Training result
  data/config/config.txt
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/TrainingController.java
  src/main/java/com/app/controllers/menuactions/AddTrainingResultMenuAction.java
  src/main/java/com/app/controllers/menuactions/CompetitionSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/CreateTrainingMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/TrainingMenuAction.java
  src/main/java/com/app/controllers/menuactions/ViewTrainingResultsMenuAction.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/models/TrainingModel.java
  src/main/java/com/app/models/services/TrainingService.java
  src/main/java/com/app/views/TrainingView.java
Labels: new-feature

#96 Resultcontroller
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/DisciplinesController.java
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/ResultController.java
  src/main/java/com/app/models/CompetitionModel.java
  src/main/java/com/app/views/ResultView.java
Labels: enhancement

#95 Membercleanuppayment
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MembershipController.java
  src/main/java/com/app/controllers/PaymentController.java
  src/main/java/com/app/controllers/menuactions/PaymentRequestMenuAction.java
  src/main/java/com/app/controllers/menuactions/PaymentSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/RenewalRequestMenuAction.java
  src/main/java/com/app/models/MembershipModel.java
  src/test/java/com/app/models/MembershipModelTest.java
Labels: enhancement

#97 added new uml
  other/uml-create-member
Labels: enhancement

#101 validate age
  src/main/java/com/app/models/InputModel.java
  src/main/java/com/app/models/MemberModel.java
  src/test/java/com/app/models/ValidateModelTest.java
Labels: bug-fix, enhancement

#99 Table view
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MenuController.java
  src/main/java/com/app/views/MenuView.java
  src/main/java/com/app/views/TableView.java
  src/main/java/com/app/views/View.java
Labels: bug-fix, enhancement, new-feature

#100 added some filtering to the top 5, WIP
  src/main/java/com/app/controllers/LeaderboardController.java
Labels: enhancement

#102 Membertodiscipline
  src/main/java/com/app/controllers/DisciplinesController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/ResultController.java
  src/main/java/com/app/controllers/menuactions/EditMemberMenuAction.java
  src/main/java/com/app/controllers/menuactions/MemberSubMenuMenuAction.java
Labels: enhancement

#103 Seniority
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/models/MemberModel.java
Labels: new-feature

#105 Fixes - fixed bug with new age validator
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/models/InputModel.java
  src/test/java/com/app/models/ValidateModelTest.java
Labels: bug-fix, enhancement

#104 Fix comp
  data/config/config.txt
  src/main/java/com/app/App.java
  src/main/java/com/app/controllers/CompetitionController.java
  src/main/java/com/app/controllers/DisciplineController.java
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/ResultController.java
  src/main/java/com/app/controllers/SwimEventController.java
  src/main/java/com/app/controllers/TrainingController.java
  src/main/java/com/app/controllers/menuactions/AddResultMenuAction.java
  src/main/java/com/app/controllers/menuactions/AddTrainingResultMenuAction.java
  src/main/java/com/app/controllers/menuactions/CompetitionSubMenuAction.java
  src/main/java/com/app/controllers/menuactions/CreateCompetitionSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/CreateTrainingMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/PracticeMenuAction.java
  src/main/java/com/app/controllers/menuactions/SwimEventSubMenuMenuAction.java
  src/main/java/com/app/controllers/menuactions/TrainingMenuAction.java
  src/main/java/com/app/controllers/menuactions/ViewResultsMenuAction.java
  src/main/java/com/app/controllers/menuactions/ViewTrainingResultsMenuAction.java
  src/main/java/com/app/models/InputModel.java
  src/main/java/com/app/models/ResultModel.java
  src/main/java/com/app/models/SwimEventModel.java
  src/main/java/com/app/models/TrainingModel.java
  src/main/java/com/app/models/services/CompetitionService.java
  src/main/java/com/app/models/services/SwimEventService.java
  src/main/java/com/app/models/services/TrainingService.java
  src/main/java/com/app/views/SwimEventView.java
  src/main/java/com/app/views/TrainingView.java
  src/test/java/com/app/controllers/DisciplineControllerTest.java
  src/test/java/com/app/models/SwimEventModelTest.java
Labels: big, enhancement

#107 Fix practice and competitions diffence
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/SwimEventController.java
Labels: bug-fix

#108 added schoolfile
  other/introduction-and-delimations.md
Labels: new-feature

#109 add javadocs
  other/ClassDiagram.md
  src/main/java/com/app/App.java
  src/main/java/com/app/Main.java
  src/main/java/com/app/controllers/DisciplineController.java
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/MenuController.java
  src/main/java/com/app/controllers/ResultController.java
  src/main/java/com/app/models/InputModel.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MenuModel.java
  src/main/java/com/app/models/PricingModel.java
  src/main/java/com/app/models/SwimEventModel.java
  src/main/java/com/app/models/services/ConfigService.java
  src/main/java/com/app/models/services/FileService.java
  src/main/java/com/app/models/services/MemberService.java
  src/main/java/com/app/models/services/ObjectService.java
  src/main/java/com/app/models/services/PaymentService.java
  src/main/java/com/app/models/services/SwimEventService.java
  src/main/java/com/app/models/types/AgeGroupType.java
  src/main/java/com/app/views/TableView.java
  src/main/java/com/app/views/View.java
  src/main/java/com/app/views/types/ColorKeyType.java
  src/main/java/com/app/views/types/ColorTextType.java
Labels: enhancement

#110 Swim event fix
  src/main/java/com/app/controllers/LeaderboardController.java
Labels: bug-fix

#112 updated classdiagram
  other/ClassDiagram.md
Labels: enhancement

#116 Todos
  src/main/java/com/app/controllers/DisciplineController.java
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/PaymentController.java
  src/main/java/com/app/controllers/ResultController.java
  src/main/java/com/app/controllers/SwimEventController.java
  src/main/java/com/app/models/DisciplineModel.java
Labels: enhancement

#115 added out.txt to config file
  src/main/java/com/app/controllers/PaymentController.java
Labels: bug-fix

#114 Fix TODOs
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/PaymentController.java
  src/main/java/com/app/controllers/SwimEventController.java
  src/main/java/com/app/models/MemberModel.java
  src/main/java/com/app/models/MembershipModel.java
  src/main/java/com/app/models/SwimEventModel.java
  src/main/java/com/app/models/services/ConfigService.java
  src/main/java/com/app/models/services/FileService.java
  src/main/java/com/app/models/services/PaymentService.java
  src/main/java/com/app/views/PaymentsView.java
  src/main/java/com/app/views/SwimEventView.java
  src/test/java/com/app/controllers/PaymentControllerTest.java
  src/test/java/com/app/models/MemberModelTest.java
  src/test/java/com/app/models/MembershipModelTest.java
Labels: enhancement

#119 Fixes
  src/main/java/com/app/controllers/InputController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/SwimEventController.java
  src/main/java/com/app/controllers/menuactions/ViewMemberMenuAction.java
Labels: bug-fix

#118 added user feedback for payment management
  src/main/java/com/app/controllers/LeaderboardController.java
  src/main/java/com/app/controllers/MemberController.java
  src/main/java/com/app/controllers/PaymentController.java
  src/main/java/com/app/controllers/PredictionController.java
Labels: enhancement

#120 fixed viewResulst with no events
  src/main/java/com/app/controllers/SwimEventController.java
Labels: enhancement

#121 Fix bugs reported by codacy
  src/main/java/com/app/controllers/MemberController.java
Labels: enhancement

#122 Other files
  other/Delfinen.pptx
  other/create-member-classdiagram-sample.svg
  other/domain-model.svg
  other/full-classdiagram.md
  other/full-classdiagram.svg
  other/introduction-and-delimations.md
  other/softwareudvikling.pdf
  other/uml-create-member.md
  other/virksomhed.pdf
Labels: enhancement
